add changelogs for 3.0.6-3.0.8, fix user agent
vimeo/vimeo.php pull request #291
Opened 2021-05-03 16:51 UTC by aaronm67

correctly reflect version # in user-agent.

2021-05-03 17:45 UTC, tommypenner requested changes
Fixed dates

2021-05-03 17:45 UTC, tommypenner commented on CHANGELOG.md
> +## [3.0.8] - 2019-12-11
```suggestion
## [3.0.8] - 2021-05-03
```

2021-05-03 17:45 UTC, tommypenner commented on CHANGELOG.md
> +## [3.0.7] - 2019-12-11
```suggestion
## [3.0.7] - 2021-04-28
```

2021-05-03 17:45 UTC, tommypenner commented on CHANGELOG.md
> +## [3.0.6] - 2019-12-11
```suggestion
## [3.0.6] - 2020-06-20
```

2021-05-03 17:47 UTC, aaronm67 commented on CHANGELOG.md
> +## [3.0.8] - 2019-12-11
Oops, thanks - I didn't even  notice there were dates on there.

2021-05-04 16:35 UTC, Sventour approved these changes

2021-05-04 17:11 UTC, nbeliard approved these changes
LGTM

2021-05-04 17:13 UTC, tommypenner approved these changes

2021-05-04 17:15 UTC, merged